/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FurnitureWebsiteIndexImport } from './routes/furniture-website/index'
import { Route as CourseWebsiteIndexImport } from './routes/course-website/index'

// Create/Update Routes

const FurnitureWebsiteIndexRoute = FurnitureWebsiteIndexImport.update({
  path: '/furniture-website/',
  getParentRoute: () => rootRoute,
} as any)

const CourseWebsiteIndexRoute = CourseWebsiteIndexImport.update({
  path: '/course-website/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/course-website/': {
      preLoaderRoute: typeof CourseWebsiteIndexImport
      parentRoute: typeof rootRoute
    }
    '/furniture-website/': {
      preLoaderRoute: typeof FurnitureWebsiteIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  CourseWebsiteIndexRoute,
  FurnitureWebsiteIndexRoute,
])

/* prettier-ignore-end */
