/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProteinWebsiteIndexImport } from './routes/protein-website/index'
import { Route as MedicalWebsiteIndexImport } from './routes/medical-website/index'
import { Route as HestechMobileIndexImport } from './routes/hestech-mobile/index'
import { Route as FurnitureWebsiteIndexImport } from './routes/furniture-website/index'
import { Route as CourseWebsiteIndexImport } from './routes/course-website/index'

// Create/Update Routes

const ProteinWebsiteIndexRoute = ProteinWebsiteIndexImport.update({
  path: '/protein-website/',
  getParentRoute: () => rootRoute,
} as any)

const MedicalWebsiteIndexRoute = MedicalWebsiteIndexImport.update({
  path: '/medical-website/',
  getParentRoute: () => rootRoute,
} as any)

const HestechMobileIndexRoute = HestechMobileIndexImport.update({
  path: '/hestech-mobile/',
  getParentRoute: () => rootRoute,
} as any)

const FurnitureWebsiteIndexRoute = FurnitureWebsiteIndexImport.update({
  path: '/furniture-website/',
  getParentRoute: () => rootRoute,
} as any)

const CourseWebsiteIndexRoute = CourseWebsiteIndexImport.update({
  path: '/course-website/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/course-website/': {
      preLoaderRoute: typeof CourseWebsiteIndexImport
      parentRoute: typeof rootRoute
    }
    '/furniture-website/': {
      preLoaderRoute: typeof FurnitureWebsiteIndexImport
      parentRoute: typeof rootRoute
    }
    '/hestech-mobile/': {
      preLoaderRoute: typeof HestechMobileIndexImport
      parentRoute: typeof rootRoute
    }
    '/medical-website/': {
      preLoaderRoute: typeof MedicalWebsiteIndexImport
      parentRoute: typeof rootRoute
    }
    '/protein-website/': {
      preLoaderRoute: typeof ProteinWebsiteIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  CourseWebsiteIndexRoute,
  FurnitureWebsiteIndexRoute,
  HestechMobileIndexRoute,
  MedicalWebsiteIndexRoute,
  ProteinWebsiteIndexRoute,
])

/* prettier-ignore-end */
